import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./Nav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const jetbrainsMono = localFont({
  src: "../app/fonts/JetBrainsMono-Bold.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.className} antialiased`}
      >
        <main>
          <Nav/>
          {children}
        </main>
      </body>
    </html>
  );
}
